<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="sell.aspx.cs" Inherits="ArtHub.sell" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            height: 61px;
            font-size: xx-large;
            text-align: center;
        }
        .auto-style3 {
            height: 45px;
        }
        .auto-style4 {
            height: 64px;
        }
        .auto-style5 {
            height: 65px;
        }
        .auto-style6 {
            height: 62px;
        }
        .auto-style7 {
            height: 64px;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        
        <table class="auto-style1">
            <tr>
                <td class="auto-style2">Artist Art Info</td>
            </tr>
            <tr>
                <td class="auto-style3">Artist name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp;
                    <asp:TextBox ID="Aname" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style4">Upload&nbsp; img&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;&nbsp;
                    <asp:FileUpload ID="Uimg" runat="server" />
                </td>
            </tr>
            <tr>
                <td class="auto-style5">Art Description&nbsp; :&nbsp;
                    <asp:TextBox ID="Ades" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">Art Price&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :&nbsp;
                    <asp:TextBox ID="Aprice" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style6">EmailAddress&nbsp;&nbsp;&nbsp; :&nbsp;
                    <asp:TextBox ID="eadd" runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="auto-style7">
                    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="submit" />
                &nbsp;
                    <asp:Button ID="editinfo" runat="server"  Text="Edit" OnClick="editinfo_Click" />
                &nbsp;<asp:Button ID="Button3" runat="server"  Text="Reset" />
                </td>
            </tr>
        </table>
        <asp:GridView ID="gvSell" runat="server" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnRowDeleting="gvSell_RowDeleting" OnSelectedIndexChanged="gvSell_SelectedIndexChanged">
            <Columns>
                <asp:ImageField DataImageUrlField="Upload_img" HeaderText="ART" ControlStyle-Height="100px" ControlStyle-Width="100px">
                </asp:ImageField>
            </Columns>
        </asp:GridView>
        <%--<asp:SqlDataSource ID="MyDataSource" runat="server"></asp:SqlDataSource>--%>
    </form>
</body>
</html>
